// Copyright by MF

#pragma once

#include "NativeGameplayTags.h"

namespace WarriorGameplayTags
{
	/** Input Tags**/
	UDEMY_TRAINING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	UDEMY_TRAINING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	UDEMY_TRAINING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	UDEMY_TRAINING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipAxe);
	UDEMY_TRAINING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnEquipAxe);

	/** Player Tags**/
	UDEMY_TRAINING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Axe);
}
