// Copyright by MF

#pragma once

#include "NativeGameplayTags.h"

namespace WarriorGameplayTags
{
	/** Input Tags**/
	UDEMY_TRAINING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	UDEMY_TRAINING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	UDEMY_TRAINING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	UDEMY_TRAINING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipAxe);
	UDEMY_TRAINING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnEquipAxe);
	UDEMY_TRAINING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack_Axe);
	UDEMY_TRAINING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HeavyAttack_Axe);
	
	/** Player Tags**/
	UDEMY_TRAINING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Axe);
	UDEMY_TRAINING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Axe);
	UDEMY_TRAINING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light_Axe);
	UDEMY_TRAINING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Heavy_Axe);
	UDEMY_TRAINING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Axe);
	UDEMY_TRAINING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Axe);
	UDEMY_TRAINING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_Axe);
	UDEMY_TRAINING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_JumpToFinisher);

	/** Enemy Tags**/
	UDEMY_TRAINING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Weapon);

	/** Shared Tags**/
	UDEMY_TRAINING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_MeleeHit);

}
